using UnityEngine;
using UnityEngine.UI;

public class ColorTransitioner : MonoBehaviour
{
    [SerializeField]
    private Image _image = default; // ”wŒi‰æ‘œ

    [SerializeField]
    private Color _to = default; // ‚±‚ÌF‚É‘JˆÚ‚·‚é

    [SerializeField]
    private float _duration = 1; // ‘JˆÚŠÔi•bj

    private Color _from;
    private float _elapsed = 0;

    /// <summary>
    /// ”wŒiF‚Ì‘JˆÚ‚ªŠ®—¹‚µ‚Ä‚¢‚é‚©‚Ç‚¤‚©
    /// </summary>
    public bool IsCompleated
        => _image == null ? false : _image.color == _to;

    void Start()
    {
        if (_image == null) { return; }
        _from = _image.color;
    }

    void Update()
    {
        if (_image == null) { return; }
        _elapsed += Time.deltaTime;
        if (_elapsed < _duration)
        {
            _image.color = Color.Lerp(_from, _to, _elapsed / _duration);
        }
        else
        {
            _image.color = _to;
        }
    }

    /// <summary>
    /// ”wŒiF‚Ì‘JˆÚˆ—‚ğŠJn‚·‚é
    /// </summary>
    /// <param name="color"></param>
    public void Play(Color color)
    {
        if (_image == null) { return; }

        _from = _image.color;
        _to = color;
        _elapsed = 0;
    }

    /// <summary>
    /// Œ»İ‚Ì”wŒiF‘JˆÚˆ—‚ğƒXƒLƒbƒv‚·‚é
    /// </summary>
    public void Skip()
    {
        _elapsed = _duration;
    }
}